<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_x5qBwPSMEeeYpYD60oU_zA" name="OnBoardingValidation" author="romain" bonitaVersion="7.8.3" bonitaModelVersion="7.8.3-001" configId="ACED00057400244F6E426F617264696E6756616C69646174696F6E372E382E332D303031372E382E337370">
    <elements xmi:type="process:Pool" xmi:id="_x5qBwfSMEeeYpYD60oU_zA" name="OnBoardingValidation">
      <elements xmi:type="process:Lane" xmi:id="_x5qByPSMEeeYpYD60oU_zA" name="Bank" actor="_x5qCI_SMEeeYpYD60oU_zA">
        <elements xmi:type="process:Task" xmi:id="_x5qB2fSMEeeYpYD60oU_zA" name="Investigate onboarding request" outgoing="_hi4VwEclEeml4OmTM0FgHg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x5qB2_SMEeeYpYD60oU_zA" name="displayName()" content="return &quot;&amp;#128269;  Investigate request, Case ID: &quot;+processInstanceId;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_hMSCgE8CEeiL57cXslApDw" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
          </dynamicLabel>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x5qB3PSMEeeYpYD60oU_zA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x5qB3fSMEeeYpYD60oU_zA" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_vBZpQAHUEeiNfNN2BDEehQ" name="$activityState" transient="true" datasourceId="IN_MEMORY" dataType="_x5qCOfSMEeeYpYD60oU_zA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_zJa4cAHdEeiNfNN2BDEehQ" name="Required" content="Required" interpreter="GROOVY"/>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x5qB3vSMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x5qB3_SMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x5qB4PSMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x5qB4fSMEeeYpYD60oU_zA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x5qB4vSMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_x5qB5fSMEeeYpYD60oU_zA">
            <targetForm xmi:type="expression:Expression" xmi:id="_6incgPYJEeesarEo_Te_Dg" name="AddCommentForm" content="f6298197-360b-4e2c-87f0-1252b0e31adc" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_x5qB5_SMEeeYpYD60oU_zA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_x5qB6PSMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_x5qB-fSMEeeYpYD60oU_zA" name="Custom Activity" type="STANDARD" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x5qB-_SMEeeYpYD60oU_zA" name="displayName()" content="&quot;&lt;span class=\&quot;glyphicon glyphicon-plus-sign\&quot; aria-hidden=\&quot;true\&quot;>&lt;/span> Create activitiy&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x5qB_PSMEeeYpYD60oU_zA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x5qB_fSMEeeYpYD60oU_zA" name="descriptionAfterCompletion()" content="&quot;Activity created: '$name'&quot;.toString()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_I5DOMPYYEeesarEo_Te_Dg" name="name">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_I5DOMfYYEeesarEo_Te_Dg"/>
            </referencedElements>
          </stepSummary>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x5qB_vSMEeeYpYD60oU_zA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x5qB__SMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x5qCAPSMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x5qCAfSMEeeYpYD60oU_zA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x5qCAvSMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_x5qCBfSMEeeYpYD60oU_zA" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_6Z3hYCenEei7d4O1CuuFSg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_x5qCB_SMEeeYpYD60oU_zA">
            <inputs xmi:type="process:ContractInput" xmi:id="_0zvXsPYVEeesarEo_Te_Dg" name="name">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_0zvXsfYVEeesarEo_Te_Dg"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_x5qCCPSMEeeYpYD60oU_zA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HGQf8PUdEeeREboOt7l4UQ" name="Call Customer activity" type="STANDARD" testBefore="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HGUxYfUdEeeREboOt7l4UQ" name="displayName()" content="return &quot;&amp;#128241; Call customer, Case ID: &quot; +processInstanceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_btrr0E8CEeiL57cXslApDw" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
          </dynamicLabel>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HGUxYPUdEeeREboOt7l4UQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HGUxYvUdEeeREboOt7l4UQ" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_fjNc8AHUEeiNfNN2BDEehQ" name="$activityState" transient="true" datasourceId="IN_MEMORY" dataType="_x5qCOfSMEeeYpYD60oU_zA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_wd1b8AHdEeiNfNN2BDEehQ" name="Discretionary" content="Discretionary" interpreter="GROOVY"/>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HGUxZvUdEeeREboOt7l4UQ" name="loopWhileUnresolved()" content="import org.bonitasoft.engine.bpm.flownode.ArchivedActivityInstanceSearchDescriptor&#xA;import org.bonitasoft.engine.search.SearchOptionsBuilder&#xA;&#xA;apiAccessor.getProcessAPI().searchArchivedActivities(new SearchOptionsBuilder(0, 1).with {&#xA;&#x9;   filter(ArchivedActivityInstanceSearchDescriptor.PARENT_PROCESS_INSTANCE_ID, processInstanceId)&#xA;&#x9;   filter(ArchivedActivityInstanceSearchDescriptor.NAME, &quot;Resolve&quot;)&#xA;&#x9;   done()&#xA;&#x9;}).count == 0" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="__PJhYEntEeiGG-is-nFnUg" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
            <referencedElements xmi:type="expression:Expression" xmi:id="__PJhYUntEeiGG-is-nFnUg" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="com.bonitasoft.engine.api.APIAccessor"/>
          </loopCondition>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HGUxZ_UdEeeREboOt7l4UQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HGUxaPUdEeeREboOt7l4UQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HGVYcfUdEeeREboOt7l4UQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HGVYcPUdEeeREboOt7l4UQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HGVYc_UdEeeREboOt7l4UQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_6incgvYJEeesarEo_Te_Dg" name="AddCommentForm" content="f6298197-360b-4e2c-87f0-1252b0e31adc" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HGVYcvUdEeeREboOt7l4UQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HGVYdfUdEeeREboOt7l4UQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Eef9MPYSEeesarEo_Te_Dg" name="Dymanic Activity Container" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_UF8iCODjEeioZo4elrUmvw" source="_t2k0cPYZEeesarEo_Te_Dg"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EejnkfYSEeesarEo_Te_Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EejnkPYSEeesarEo_Te_Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EejnkvYSEeesarEo_Te_Dg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EejnlvYSEeesarEo_Te_Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Eejnl_YSEeesarEo_Te_Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EejnmPYSEeesarEo_Te_Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EejnmvYSEeesarEo_Te_Dg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EejnmfYSEeesarEo_Te_Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_EekOofYSEeesarEo_Te_Dg" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_FoCMIidqEeida-blYETd7g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_EekOoPYSEeesarEo_Te_Dg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_EekOo_YSEeesarEo_Te_Dg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_t2k0cPYZEeesarEo_Te_Dg" text="Technical workaround to create Manual task"/>
        <elements xmi:type="process:CallActivity" xmi:id="_14GNUEcjEeml4OmTM0FgHg" name="Sign Contract" outgoing="_14IpnEcjEeml4OmTM0FgHg" incoming="_14KeykcjEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_14GNUUcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_14GNUkcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_14GNU0cjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_14GNVEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_14GNVUcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_14GNVkcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_14GNV0cjEeml4OmTM0FgHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_14GNWEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_14GNWUcjEeml4OmTM0FgHg" subprocessTarget="customer" assignationType="Data">
            <processSource xmi:type="expression:Expression" xmi:id="_14GNWkcjEeml4OmTM0FgHg" name="customer" content="customer" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_14GNW0cjEeml4OmTM0FgHg" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
            </processSource>
          </inputMappings>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_14GNXEcjEeml4OmTM0FgHg" name="Signature" content="Signature" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_14GNXUcjEeml4OmTM0FgHg" name="2.1.0" content="2.1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_14GNaUcjEeml4OmTM0FgHg" name="Is Scoring valid ?" outgoing="_14J3sEcjEeml4OmTM0FgHg _14KewEcjEeml4OmTM0FgHg" incoming="_hi4VwEclEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_14GNakcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_14GNa0cjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_14GNbEcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_14HbcEcjEeml4OmTM0FgHg" name="Generate and send contract" outgoing="_14KeykcjEeml4OmTM0FgHg" incoming="_14KewEcjEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_14HbcUcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_14HbckcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_14Hbc0cjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_14HbdEcjEeml4OmTM0FgHg" documentation="Generate new customer contract using template and customer provided data." name="Generate contract from template" definitionId="document-templating" event="ON_ENTER" definitionVersion="1.0.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_14HbdUcjEeml4OmTM0FgHg" definitionId="document-templating" version="1.0.1" modelVersion="7.6.0-002">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbdkcjEeml4OmTM0FgHg" key="documentInput">
                <expression xmi:type="expression:Expression" xmi:id="_14Hbd0cjEeml4OmTM0FgHg" name="templateContract" content="templateContract" type="DOCUMENT_REF_TYPE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Document" xmi:id="_14HbeEcjEeml4OmTM0FgHg" name="templateContract"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbeUcjEeml4OmTM0FgHg" key="replacements">
                <expression xmi:type="expression:TableExpression" xmi:id="_14HbekcjEeml4OmTM0FgHg">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_14Hbe0cjEeml4OmTM0FgHg">
                    <expressions xmi:type="expression:Expression" xmi:id="_14HbfEcjEeml4OmTM0FgHg" name="customer" content="customer" returnTypeFixed="true"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_14HbfUcjEeml4OmTM0FgHg" name="customer" content="customer" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_14HbfkcjEeml4OmTM0FgHg" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
                    </expressions>
                  </expressions>
                  <expressions xmi:type="expression:ListExpression" xmi:id="_14Hbf0cjEeml4OmTM0FgHg">
                    <expressions xmi:type="expression:Expression" xmi:id="_14HbgEcjEeml4OmTM0FgHg" name="date" content="date" returnTypeFixed="true"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_14HbgUcjEeml4OmTM0FgHg" name="todayDate" content="import java.time.LocalDate&#xA;import java.time.format.DateTimeFormatter&#xA;&#xA;LocalDate localDate = LocalDate.now()&#xA;DateTimeFormatter formatter = DateTimeFormatter.ofPattern(&quot;MM/dd/yyyy&quot;)&#xA;localDate.format(formatter)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbgkcjEeml4OmTM0FgHg" key="outputFileName">
                <expression xmi:type="expression:Expression" xmi:id="_14Hbg0cjEeml4OmTM0FgHg" name="contract.docx" content="contract.docx" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_14HbhEcjEeml4OmTM0FgHg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_14HbhUcjEeml4OmTM0FgHg" name="contract" content="contract" type="DOCUMENT_REF_TYPE">
                <referencedElements xmi:type="process:Document" xmi:id="_14HbhkcjEeml4OmTM0FgHg" name="contract"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_14Hbh0cjEeml4OmTM0FgHg" name="document" content="document" type="CONNECTOR_OUTPUT_TYPE" returnType="org.bonitasoft.engine.bpm.document.DocumentValue">
                <referencedElements xmi:type="definition:Output" xmi:id="_14HbiEcjEeml4OmTM0FgHg" name="document" type="org.bonitasoft.engine.bpm.document.DocumentValue"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_14HbiUcjEeml4OmTM0FgHg" type="DOCUMENT_CREATE_UPDATE"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_14HbikcjEeml4OmTM0FgHg" documentation="Convert contract from Word file format to PDF" name="Convert contract to PDF" definitionId="document-converter" event="ON_ENTER" definitionVersion="1.0.2">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_14Hbi0cjEeml4OmTM0FgHg" definitionId="document-converter" version="1.0.2" modelVersion="7.6.0-002">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbjEcjEeml4OmTM0FgHg" key="sourceDocument">
                <expression xmi:type="expression:Expression" xmi:id="_14HbjUcjEeml4OmTM0FgHg" name="contract" content="contract" type="DOCUMENT_REF_TYPE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Document" xmi:id="_14HbjkcjEeml4OmTM0FgHg" name="contract"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14Hbj0cjEeml4OmTM0FgHg" key="encoding">
                <expression xmi:type="expression:Expression" xmi:id="_14HbkEcjEeml4OmTM0FgHg" name="windows-1252" content="windows-1252" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbkUcjEeml4OmTM0FgHg" key="outputFileName">
                <expression xmi:type="expression:Expression" xmi:id="_14HbkkcjEeml4OmTM0FgHg" name="contract.pdf" content="contract.pdf" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_14Hbk0cjEeml4OmTM0FgHg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_14HblEcjEeml4OmTM0FgHg" name="contract" content="contract" type="DOCUMENT_REF_TYPE">
                <referencedElements xmi:type="process:Document" xmi:id="_14HblUcjEeml4OmTM0FgHg" name="contract"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_14HblkcjEeml4OmTM0FgHg" name="outputDocumentValue" content="outputDocumentValue" type="CONNECTOR_OUTPUT_TYPE" returnType="org.bonitasoft.engine.bpm.document.DocumentValue">
                <referencedElements xmi:type="definition:Output" xmi:id="_14Hbl0cjEeml4OmTM0FgHg" name="outputDocumentValue" type="org.bonitasoft.engine.bpm.document.DocumentValue"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_14HbmEcjEeml4OmTM0FgHg" type="DOCUMENT_CREATE_UPDATE"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_14HbmUcjEeml4OmTM0FgHg" documentation="Send the contract to DocuSign service to allow customer digital signature." name="Send contract PDF to DocuSign" definitionId="coSignSend" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_14HbmkcjEeml4OmTM0FgHg" definitionId="coSignSend" version="1.0.0" modelVersion="7.6.0-002">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14Hbm0cjEeml4OmTM0FgHg" key="authUserName">
                <expression xmi:type="expression:Expression" xmi:id="_14HbnEcjEeml4OmTM0FgHg" name="docusignUsername" content="docusignUsername" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_14HbnUcjEeml4OmTM0FgHg" name="docusignUsername" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbnkcjEeml4OmTM0FgHg" key="authUserPass">
                <expression xmi:type="expression:Expression" xmi:id="_14Hbn0cjEeml4OmTM0FgHg" name="docusignPassword" content="docusignPassword" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_14HboEcjEeml4OmTM0FgHg" name="docusignPassword" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HboUcjEeml4OmTM0FgHg" key="authIntegratorKey">
                <expression xmi:type="expression:Expression" xmi:id="_14HbokcjEeml4OmTM0FgHg" name="docusignAuthIntegratorKey" content="docusignAuthIntegratorKey" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_14Hbo0cjEeml4OmTM0FgHg" name="docusignAuthIntegratorKey" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbpEcjEeml4OmTM0FgHg" key="file">
                <expression xmi:type="expression:Expression" xmi:id="_14HbpUcjEeml4OmTM0FgHg" name="contract" content="contract" type="DOCUMENT_REF_TYPE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Document" xmi:id="_14HbpkcjEeml4OmTM0FgHg" name="contract"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14Hbp0cjEeml4OmTM0FgHg" key="fileTargetName">
                <expression xmi:type="expression:Expression" xmi:id="_14HbqEcjEeml4OmTM0FgHg" name="signed-contract.pdf" content="signed-contract.pdf" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbqUcjEeml4OmTM0FgHg" key="emailSubjet">
                <expression xmi:type="expression:Expression" xmi:id="_14HbqkcjEeml4OmTM0FgHg" name="Your new checking account" content="Your new checking account" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14Hbq0cjEeml4OmTM0FgHg" key="emailContent">
                <expression xmi:type="expression:Expression" xmi:id="_14HbrEcjEeml4OmTM0FgHg" name="generateEmailContent()" content="return &quot;&quot;&quot;Hi $customer.firstName $customer.lastName,&#xA;&#xA;Please review and sign your new checking account contract.&quot;&quot;&quot;.toString()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_14HbrUcjEeml4OmTM0FgHg" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbrkcjEeml4OmTM0FgHg" key="destMail">
                <expression xmi:type="expression:Expression" xmi:id="_14Hbr0cjEeml4OmTM0FgHg" name="customer - Customer#getEMailAddress" content="getEMailAddress" type="TYPE_JAVA_METHOD_CALL" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_14HbsEcjEeml4OmTM0FgHg" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbsUcjEeml4OmTM0FgHg" key="destName">
                <expression xmi:type="expression:Expression" xmi:id="_14HbskcjEeml4OmTM0FgHg" name="fullName()" content="&quot;&quot;&quot;${customer.firstName} ${customer.middleName} ${customer.lastName} &quot;&quot;&quot;.toString()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_14Hbs0cjEeml4OmTM0FgHg" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14HbtEcjEeml4OmTM0FgHg" key="destAccountId">
                <expression xmi:type="expression:Expression" xmi:id="_14HbtUcjEeml4OmTM0FgHg" name="docusignAccountId" content="docusignAccountId" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_14HbtkcjEeml4OmTM0FgHg" name="docusignAccountId" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14Hbt0cjEeml4OmTM0FgHg" key="path">
                <expression xmi:type="expression:Expression" xmi:id="_14HbuEcjEeml4OmTM0FgHg" name="https://demo.docusign.net/restapi" content="https://demo.docusign.net/restapi" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_14HbuUcjEeml4OmTM0FgHg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_14HbukcjEeml4OmTM0FgHg" name="customer" content="customer" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_14Hbu0cjEeml4OmTM0FgHg" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_14HbvEcjEeml4OmTM0FgHg" name="envelopeId" content="envelopeId" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_14HbvUcjEeml4OmTM0FgHg" name="envelopeId" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_14HbvkcjEeml4OmTM0FgHg" type="JAVA_METHOD" expression="setContractDocusignId">
                <inputTypes>java.lang.String</inputTypes>
              </operator>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_14Hbv0cjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_14HbwEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_14HbwUcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_14HbwkcjEeml4OmTM0FgHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_14Hbw0cjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_14ICgEcjEeml4OmTM0FgHg" name="Save document to CMS" outgoing="_hDhOUEcnEeml4OmTM0FgHg" incoming="_14LF0EcjEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_14ICgUcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_14ICgkcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_14ICg0cjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_14IChEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_14IChUcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_14IChkcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_14ICh0cjEeml4OmTM0FgHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_14ICiEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_14ICjEcjEeml4OmTM0FgHg" name="Get signed version of the contract" outgoing="_14LF0EcjEeml4OmTM0FgHg" incoming="_14IpnEcjEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_14ICjUcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_14ICjkcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_14ICj0cjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_14ICkEcjEeml4OmTM0FgHg" documentation="Get the latest version of the document from DocuSign platform." name="Get signed version of the contract from DocuSign" definitionId="coSignGetEnv" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_14ICkUcjEeml4OmTM0FgHg" definitionId="coSignGetEnv" version="1.0.0" modelVersion="7.6.0-002">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14ICkkcjEeml4OmTM0FgHg" key="authUserName">
                <expression xmi:type="expression:Expression" xmi:id="_14ICk0cjEeml4OmTM0FgHg" name="docusignUsername" content="docusignUsername" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_14IClEcjEeml4OmTM0FgHg" name="docusignUsername" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14IClUcjEeml4OmTM0FgHg" key="authPassword">
                <expression xmi:type="expression:Expression" xmi:id="_14IClkcjEeml4OmTM0FgHg" name="docusignPassword" content="docusignPassword" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_14ICl0cjEeml4OmTM0FgHg" name="docusignPassword" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14ICmEcjEeml4OmTM0FgHg" key="authIntegratorKey">
                <expression xmi:type="expression:Expression" xmi:id="_14ICmUcjEeml4OmTM0FgHg" name="docusignAuthIntegratorKey" content="docusignAuthIntegratorKey" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_14ICmkcjEeml4OmTM0FgHg" name="docusignAuthIntegratorKey" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14ICm0cjEeml4OmTM0FgHg" key="envelopeId">
                <expression xmi:type="expression:Expression" xmi:id="_14ICnEcjEeml4OmTM0FgHg" name="customer - Customer#getContractDocusignId" content="getContractDocusignId" type="TYPE_JAVA_METHOD_CALL" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_14ICnUcjEeml4OmTM0FgHg" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14ICnkcjEeml4OmTM0FgHg" key="fileTargetName">
                <expression xmi:type="expression:Expression" xmi:id="_14ICn0cjEeml4OmTM0FgHg" name="contract-signed.pdf" content="contract-signed.pdf" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_14ICoEcjEeml4OmTM0FgHg" key="path">
                <expression xmi:type="expression:Expression" xmi:id="_14ICoUcjEeml4OmTM0FgHg" name="https://demo.docusign.net/restapi" content="https://demo.docusign.net/restapi" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_14ICokcjEeml4OmTM0FgHg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_14ICo0cjEeml4OmTM0FgHg" name="contract" content="contract" type="DOCUMENT_REF_TYPE">
                <referencedElements xmi:type="process:Document" xmi:id="_14ICpEcjEeml4OmTM0FgHg" name="contract"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_14ICpUcjEeml4OmTM0FgHg" name="env" content="env" type="CONNECTOR_OUTPUT_TYPE" returnType="org.bonitasoft.engine.bpm.document.DocumentValue">
                <referencedElements xmi:type="definition:Output" xmi:id="_14ICpkcjEeml4OmTM0FgHg" name="env" type="org.bonitasoft.engine.bpm.document.DocumentValue"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_14ICp0cjEeml4OmTM0FgHg" type="DOCUMENT_CREATE_UPDATE"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_14ICqEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_14ICqUcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_14ICqkcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_14ICq0cjEeml4OmTM0FgHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_14ICrEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_14IpkEcjEeml4OmTM0FgHg" name="Send On-boarding refusal" outgoing="_hwrPQEcnEeml4OmTM0FgHg" incoming="_14J3sEcjEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_14IpkUcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_14IpkkcjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_14Ipk0cjEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_14IplEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_14IplUcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_14IplkcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_14Ipl0cjEeml4OmTM0FgHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_14IpmEcjEeml4OmTM0FgHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_hDc84EcnEeml4OmTM0FgHg" name="End1" incoming="_hDhOUEcnEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hDdj8EcnEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hDc84UcnEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hDdj8UcnEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_hwpaEEcnEeml4OmTM0FgHg" name="End2" incoming="_hwrPQEcnEeml4OmTM0FgHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hwpaEkcnEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hwpaEUcnEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hwpaE0cnEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_A8RNsEy8EemBcOD5CMOafw" name="Update Customer Name">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A8Sb0Uy8EemBcOD5CMOafw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A8Sb0Ey8EemBcOD5CMOafw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A8Sb0ky8EemBcOD5CMOafw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_C2oooEy8EemBcOD5CMOafw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_C2oooUy8EemBcOD5CMOafw" name="customerName" content="customerName" type="SEARCH_INDEX_TYPE">
              <referencedElements xmi:type="process:SearchIndex" xmi:id="_DV9B4Ey8EemBcOD5CMOafw">
                <name xmi:type="expression:Expression" xmi:id="_DV9B4Uy8EemBcOD5CMOafw" name="customerName" content="customerName" returnTypeFixed="true"/>
              </referencedElements>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_C2oooky8EemBcOD5CMOafw" name="newScript()" content="return customer.getFirstName() + &quot; &quot; +customer.getMiddleName()+ &quot; &quot; +customer.getLastName()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_J-gDMEy8EemBcOD5CMOafw" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_C2ooo0y8EemBcOD5CMOafw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_A8Sb00y8EemBcOD5CMOafw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_A8Sb1Ey8EemBcOD5CMOafw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_A8Sb1Uy8EemBcOD5CMOafw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_A8Sb10y8EemBcOD5CMOafw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_A8Sb1ky8EemBcOD5CMOafw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_mRGqAPUrEeeJbuCjYn0Nqw" name="customer" dataType="_x5qCPPSMEeeYpYD60oU_zA" className="com.company.model.Customer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_mRGqAfUrEeeJbuCjYn0Nqw" name="init_customer()" content="customerDAO.findByPersistenceId(Long.parseLong(customerId))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Customer">
          <referencedElements xmi:type="expression:Expression" xmi:id="_Zjas4ErrEeml4OmTM0FgHg" name="customerDAO" content="customerDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.CustomerDAO" returnTypeFixed="true"/>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Zjas4UrrEeml4OmTM0FgHg" name="customerId">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_Zjas4krrEeml4OmTM0FgHg"/>
          </referencedElements>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_x5qCE_SMEeeYpYD60oU_zA" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_5fzXYODnEeiqro8MYznsHA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_x5qCFvSMEeeYpYD60oU_zA" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_x5qCF_SMEeeYpYD60oU_zA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_14IpnEcjEeml4OmTM0FgHg" target="_14ICjEcjEeml4OmTM0FgHg" source="_14GNUEcjEeml4OmTM0FgHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_14IpnUcjEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_14IpnkcjEeml4OmTM0FgHg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_14J3sEcjEeml4OmTM0FgHg" target="_14IpkEcjEeml4OmTM0FgHg" source="_14GNaUcjEeml4OmTM0FgHg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_14J3sUcjEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_14J3skcjEeml4OmTM0FgHg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_14KewEcjEeml4OmTM0FgHg" target="_14HbcEcjEeml4OmTM0FgHg" source="_14GNaUcjEeml4OmTM0FgHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_14KewUcjEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_14KewkcjEeml4OmTM0FgHg" name="minimal_scoring" content="minimal_scoring" type="TYPE_PARAMETER" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="parameter:Parameter" xmi:id="_xem2wEzEEemBcOD5CMOafw" name="minimal_scoring" typeClassname="java.lang.Boolean"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_14KeykcjEeml4OmTM0FgHg" target="_14GNUEcjEeml4OmTM0FgHg" source="_14HbcEcjEeml4OmTM0FgHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_14Key0cjEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_14KezEcjEeml4OmTM0FgHg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_14LF0EcjEeml4OmTM0FgHg" target="_14ICgEcjEeml4OmTM0FgHg" source="_14ICjEcjEeml4OmTM0FgHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_14LF0UcjEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_14LF0kcjEeml4OmTM0FgHg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hi4VwEclEeml4OmTM0FgHg" target="_14GNaUcjEeml4OmTM0FgHg" source="_x5qB2fSMEeeYpYD60oU_zA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hi4VwUclEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_hi4VwkclEeml4OmTM0FgHg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hDhOUEcnEeml4OmTM0FgHg" target="_hDc84EcnEeml4OmTM0FgHg" source="_14ICgEcjEeml4OmTM0FgHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hDhOUUcnEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_hDh1YEcnEeml4OmTM0FgHg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hwrPQEcnEeml4OmTM0FgHg" target="_hwpaEEcnEeml4OmTM0FgHg" source="_14IpkEcjEeml4OmTM0FgHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hwrPQUcnEeml4OmTM0FgHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_hwrPQkcnEeml4OmTM0FgHg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_x5qCIvSMEeeYpYD60oU_zA" name="Customer" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_x5qCI_SMEeeYpYD60oU_zA" name="Bank"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_At93wAdeEeiGn-a9BKu52g" name="Qualification" version="7.8.3-001" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_AuA7EAdeEeiGn-a9BKu52g">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_AuA7EQdeEeiGn-a9BKu52g" name="Customer">
            <groups xmi:type="actormapping:Groups" xmi:id="_AuA7EgdeEeiGn-a9BKu52g"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_AuA7EwdeEeiGn-a9BKu52g"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_AuA7FAdeEeiGn-a9BKu52g"/>
            <users xmi:type="actormapping:Users" xmi:id="_AuA7FQdeEeiGn-a9BKu52g"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_AuA7FgdeEeiGn-a9BKu52g" name="Bank">
            <groups xmi:type="actormapping:Groups" xmi:id="_AuA7FwdeEeiGn-a9BKu52g"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_AuA7GAdeEeiGn-a9BKu52g"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_AuA7GQdeEeiGn-a9BKu52g"/>
            <users xmi:type="actormapping:Users" xmi:id="_AuA7GgdeEeiGn-a9BKu52g"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e0AdeEeiGn-a9BKu52g" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e0wdeEeiGn-a9BKu52g" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e1AdeEeiGn-a9BKu52g" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e1QdeEeiGn-a9BKu52g" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e1gdeEeiGn-a9BKu52g" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e1wdeEeiGn-a9BKu52g" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e2AdeEeiGn-a9BKu52g" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e2QdeEeiGn-a9BKu52g" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_At-e2gdeEeiGn-a9BKu52g" id="OTHER"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_ZbqSYCeQEei7d4O1CuuFSg" name="Demo" version="7.8.3-001" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_ZbqSYSeQEei7d4O1CuuFSg">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_ZbqSYieQEei7d4O1CuuFSg" name="Customer">
            <groups xmi:type="actormapping:Groups" xmi:id="_ZbqSYyeQEei7d4O1CuuFSg">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_ZbqSZCeQEei7d4O1CuuFSg"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_ZbqSZSeQEei7d4O1CuuFSg"/>
            <users xmi:type="actormapping:Users" xmi:id="_ZbqSZieQEei7d4O1CuuFSg"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_ZbqSZyeQEei7d4O1CuuFSg" name="Bank">
            <groups xmi:type="actormapping:Groups" xmi:id="_ZbqSaCeQEei7d4O1CuuFSg">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_ZbqSaSeQEei7d4O1CuuFSg"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_ZbqSaieQEei7d4O1CuuFSg"/>
            <users xmi:type="actormapping:Users" xmi:id="_ZbqSayeQEei7d4O1CuuFSg"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_MgTo8EcnEeml4OmTM0FgHg" type="CONNECTOR" definitionId="document-templating" definitionVersion="1.0.1" implementationId="document-templating-impl" implementationVersion="1.0.1"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_MsOlEEcnEeml4OmTM0FgHg" type="CONNECTOR" definitionId="document-converter" definitionVersion="1.0.2" implementationId="document-converter-impl" implementationVersion="1.0.2"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_MuqOAEcnEeml4OmTM0FgHg" type="CONNECTOR" definitionId="coSignSend" definitionVersion="1.0.0" implementationId="coSignSend-impl" implementationVersion="1.0.0"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_MvVjcEcnEeml4OmTM0FgHg" type="CONNECTOR" definitionId="coSignGetEnv" definitionVersion="1.0.0" implementationId="coSignGetEnv-impl" implementationVersion="1.0.0"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_TzPDwE8ZEemBcOD5CMOafw" type="ACTOR_FILTER" definitionId="single-user" definitionVersion="1.0.0" implementationId="single-user-impl" implementationVersion="1.0.0"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_wPIoEeiAVslBKvhhLg" id="ACTOR_FILTER">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_TzcfIE8ZEemBcOD5CMOafw" id="single-user-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_Tze7YE8ZEemBcOD5CMOafw" key="single-user-impl -- 1.0.0" value="bonita-userfilter-single-user-impl-1.0.0-SNAPSHOT.jar" type="ACTOR_FILTER"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_wfIoEeiAVslBKvhhLg" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_MpuDoEcnEeml4OmTM0FgHg" id="document-templating-impl-1.0.1">
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqDa0EcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="bonita-connector-document-templating-impl-1.0.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqPBAEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="oro-2.0.8.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqQPIEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="itext-2.1.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqQPIUcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.template.velocity-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqQ2MEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="org.odftoolkit.odfdom.converter.xhtml-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqSEUEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.converter-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqSrYEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="commons-lang-2.4.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqVusEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="org.odftoolkit.odfdom.converter.pdf-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqVusUcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="xercesImpl-2.9.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqW80EcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="org.odftoolkit.odfdom.converter.core-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqW80UcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="odfdom-java-0.8.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqYyAEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.converter.odt.odfdom-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqaAIEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.document-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqanMEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.template-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqbOQEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.itext.extension-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Mqb1UEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.document.docx-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqccYEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="velocity-1.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqdDcEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.core-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MqdqgEcnEeml4OmTM0FgHg" key="document-templating-impl -- 1.0.1" value="fr.opensagres.xdocreport.document.odt-1.0.5.jar" type="CONNECTOR"/>
          </children>
          <children xmi:type="configuration:FragmentContainer" xmi:id="_MscAcEcnEeml4OmTM0FgHg" id="document-converter-impl-1.0.2">
            <fragments xmi:type="configuration:Fragment" xmi:id="_MssfIEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="bonita-connector-document-converter-impl-1.0.2.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MswJgEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="oro-2.0.8.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MswwkEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="itext-2.1.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MsxXoEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.template.velocity-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Msx-sEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="org.odftoolkit.odfdom.converter.xhtml-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MsylwEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.converter-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MszM0EcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="commons-lang-2.4.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms0a8EcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="xercesImpl-2.9.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms1CAEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="org.odftoolkit.odfdom.converter.pdf-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms1pEEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="poi-3.10-FINAL.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms2QIEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="org.apache.poi.xwpf.converter.core-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms23MEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="odfdom-java-0.8.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms3eQEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="org.odftoolkit.odfdom.converter.core-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms4sYEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.converter.odt.odfdom-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms5TcEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.converter.docx.xwpf-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms56gEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="org.apache.poi.xwpf.converter.xhtml-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms6hkEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.document-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms7IoEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.template-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms8WwEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="ooxml-schemas-1.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms890EcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="poi-ooxml-3.10-FINAL.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms9k4EcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.itext.extension-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms-L8EcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="org.apache.poi.xwpf.converter.pdf-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Ms-zAEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.document.docx-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MtABIEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.document.odt-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MtAoMEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="fr.opensagres.xdocreport.core-1.0.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MtDEcEcnEeml4OmTM0FgHg" key="document-converter-impl -- 1.0.2" value="velocity-1.7.jar" type="CONNECTOR"/>
          </children>
          <children xmi:type="configuration:FragmentContainer" xmi:id="_MvR5EEcnEeml4OmTM0FgHg" id="coSignSend-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_MvTuQEcnEeml4OmTM0FgHg" key="coSignSend-impl -- 1.0.0" value="coSignSend-impl-1.0.0.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_MvUVUEcnEeml4OmTM0FgHg" key="coSignSend-impl -- 1.0.0" value="libSign.jar" type="CONNECTOR"/>
          </children>
          <children xmi:type="configuration:FragmentContainer" xmi:id="_MvhwsEcnEeml4OmTM0FgHg" id="coSignGetEnv-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_MvkM8EcnEeml4OmTM0FgHg" key="coSignGetEnv-impl -- 1.0.0" value="coSignGetEnv-impl-1.0.0.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_Mvk0AEcnEeml4OmTM0FgHg" key="coSignGetEnv-impl -- 1.0.0" value="libSign.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_wvIoEeiAVslBKvhhLg" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_w_IoEeiAVslBKvhhLg" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_xPIoEeiAVslBKvhhLg" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_xfIoEeiAVslBKvhhLg" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_xvIoEeiAVslBKvhhLg" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_x_IoEeiAVslBKvhhLg" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_RlF_yPIoEeiAVslBKvhhLg" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_J-rQEEpQEeml4OmTM0FgHg" name="docusignAccountId" value="6735ceee-64f3-4e16-b1d5-df1ab305b6df" typeClassname="java.lang.String"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_J-rQEUpQEeml4OmTM0FgHg" name="docusignAuthIntegratorKey" value="f4f85187-2228-44ac-9e9a-3ee16dd18800" typeClassname="java.lang.String"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_J-rQEkpQEeml4OmTM0FgHg" name="docusignUsername" value="philippe.laumay@bonitasoft.com" typeClassname="java.lang.String"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_J-rQE0pQEeml4OmTM0FgHg" name="docusignPassword" value="Bonita_2019" typeClassname="java.lang.String"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_yB2twEzEEemBcOD5CMOafw" name="minimal_scoring" value="false" typeClassname="java.lang.Boolean"/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="_5VIq8EpPEeml4OmTM0FgHg" name="docusignAccountId" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_9hBckEpPEeml4OmTM0FgHg" name="docusignAuthIntegratorKey" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_BPvxEEpQEeml4OmTM0FgHg" name="docusignUsername" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_CpDtYEpQEeml4OmTM0FgHg" name="docusignPassword" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_wT264EzEEemBcOD5CMOafw" name="minimal_scoring" typeClassname="java.lang.Boolean"/>
      <contract xmi:type="process:Contract" xmi:id="_x5qCJPSMEeeYpYD60oU_zA">
        <inputs xmi:type="process:ContractInput" xmi:id="_HxEFkErrEeml4OmTM0FgHg" name="customerId">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_HxEFkUrrEeml4OmTM0FgHg"/>
        </inputs>
      </contract>
      <documents xmi:type="process:Document" xmi:id="_iF-48PUhEeeREboOt7l4UQ" name="caseDocuments" multiple="true">
        <mimeType xmi:type="expression:Expression" xmi:id="_iF-48fUhEeeREboOt7l4UQ" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_iF-48vUhEeeREboOt7l4UQ" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_iF-48_UhEeeREboOt7l4UQ" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="_NDK-EEcqEeml4OmTM0FgHg" name="templateContract" defaultValueIdOfDocumentStore="templateContract.docx" documentType="INTERNAL">
        <mimeType xmi:type="expression:Expression" xmi:id="_NDK-EUcqEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_NDK-EkcqEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_NDK-E0cqEeml4OmTM0FgHg" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="_dD574EpNEeml4OmTM0FgHg" name="contract">
        <mimeType xmi:type="expression:Expression" xmi:id="_dD574UpNEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_dD574kpNEeml4OmTM0FgHg" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_dD5740pNEeml4OmTM0FgHg" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_x5qCJfSMEeeYpYD60oU_zA">
        <name xmi:type="expression:Expression" xmi:id="_x5qCJvSMEeeYpYD60oU_zA" name="customerName" content="customerName" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_x5qCJ_SMEeeYpYD60oU_zA" name="" content="" interpreter="GROOVY" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_x5qCKPSMEeeYpYD60oU_zA">
        <name xmi:type="expression:Expression" xmi:id="_x5qCKfSMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_x5qCKvSMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_x5qCK_SMEeeYpYD60oU_zA">
        <name xmi:type="expression:Expression" xmi:id="_x5qCLPSMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_x5qCLfSMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_x5qCLvSMEeeYpYD60oU_zA">
        <name xmi:type="expression:Expression" xmi:id="_x5qCL_SMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_x5qCMPSMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_x5qCMfSMEeeYpYD60oU_zA">
        <name xmi:type="expression:Expression" xmi:id="_x5qCMvSMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_x5qCM_SMEeeYpYD60oU_zA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_x5qCNPSMEeeYpYD60oU_zA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_x5qCNfSMEeeYpYD60oU_zA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_x5qCNvSMEeeYpYD60oU_zA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_x5qCN_SMEeeYpYD60oU_zA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_x5qCOPSMEeeYpYD60oU_zA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_x5qCOfSMEeeYpYD60oU_zA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_x5qCOvSMEeeYpYD60oU_zA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_x5qCO_SMEeeYpYD60oU_zA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_x5qCPPSMEeeYpYD60oU_zA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_x5qCPfSMEeeYpYD60oU_zA" type="Process" element="_x5qBwPSMEeeYpYD60oU_zA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_x5qCPvSMEeeYpYD60oU_zA" type="2007" element="_x5qBwfSMEeeYpYD60oU_zA">
      <children xmi:type="notation:DecorationNode" xmi:id="_x5qCP_SMEeeYpYD60oU_zA" type="5008" element="_x5qBwfSMEeeYpYD60oU_zA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_x5qCQPSMEeeYpYD60oU_zA" type="7001" element="_x5qBwfSMEeeYpYD60oU_zA">
        <children xmi:type="notation:Node" xmi:id="_x5qCTfSMEeeYpYD60oU_zA" type="3007" element="_x5qByPSMEeeYpYD60oU_zA">
          <children xmi:type="notation:DecorationNode" xmi:id="_x5qCTvSMEeeYpYD60oU_zA" type="5007" element="_x5qByPSMEeeYpYD60oU_zA"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_x5qCT_SMEeeYpYD60oU_zA" type="7002" element="_x5qByPSMEeeYpYD60oU_zA">
            <children xmi:type="notation:Shape" xmi:id="_x5qCU_SMEeeYpYD60oU_zA" type="3005" element="_x5qB2fSMEeeYpYD60oU_zA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x5qCVPSMEeeYpYD60oU_zA" type="5005" element="_x5qB2fSMEeeYpYD60oU_zA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x5qCVfSMEeeYpYD60oU_zA" x="50" y="242" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x5qCWfSMEeeYpYD60oU_zA" type="3005" element="_x5qB-fSMEeeYpYD60oU_zA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x5qCWvSMEeeYpYD60oU_zA" type="5005" element="_x5qB-fSMEeeYpYD60oU_zA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x5qCW_SMEeeYpYD60oU_zA" x="50" y="20" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HGbfEPUdEeeREboOt7l4UQ" type="3005" element="_HGQf8PUdEeeREboOt7l4UQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HGcGIPUdEeeREboOt7l4UQ" type="5005" element="_HGQf8PUdEeeREboOt7l4UQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HGbfEfUdEeeREboOt7l4UQ" x="50" y="124" width="123" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EemD0PYSEeesarEo_Te_Dg" type="3005" element="_Eef9MPYSEeesarEo_Te_Dg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EenR8PYSEeesarEo_Te_Dg" type="5005" element="_Eef9MPYSEeesarEo_Te_Dg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EemD0fYSEeesarEo_Te_Dg" x="1688" y="461" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_t2nQsPYZEeesarEo_Te_Dg" type="3015" element="_t2k0cPYZEeesarEo_Te_Dg">
              <children xmi:type="notation:DecorationNode" xmi:id="_t2nQtfYZEeesarEo_Te_Dg" type="5010" element="_t2k0cPYZEeesarEo_Te_Dg"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_t2nQsfYZEeesarEo_Te_Dg"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_t2nQsvYZEeesarEo_Te_Dg" fontName="Ubuntu"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_t2nQs_YZEeesarEo_Te_Dg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t2nQtPYZEeesarEo_Te_Dg" x="1702" y="340" width="134" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_14GNXkcjEeml4OmTM0FgHg" type="3063" element="_14GNUEcjEeml4OmTM0FgHg" fontName="DejaVu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_14GNX0cjEeml4OmTM0FgHg" type="5093" element="_14GNUEcjEeml4OmTM0FgHg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_14GNYEcjEeml4OmTM0FgHg" x="546" y="169" width="130" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_14GNbUcjEeml4OmTM0FgHg" type="3008" element="_14GNaUcjEeml4OmTM0FgHg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_14GNbkcjEeml4OmTM0FgHg" type="5026" element="_14GNaUcjEeml4OmTM0FgHg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_14GNb0cjEeml4OmTM0FgHg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_14GNcEcjEeml4OmTM0FgHg" x="258" y="250" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_14HbxEcjEeml4OmTM0FgHg" type="3027" element="_14HbcEcjEeml4OmTM0FgHg" fontName="DejaVu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_14HbxUcjEeml4OmTM0FgHg" type="5017" element="_14HbcEcjEeml4OmTM0FgHg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_14HbxkcjEeml4OmTM0FgHg" x="378" y="175" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_14ICiUcjEeml4OmTM0FgHg" type="3027" element="_14ICgEcjEeml4OmTM0FgHg" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_14ICikcjEeml4OmTM0FgHg" type="5017" element="_14ICgEcjEeml4OmTM0FgHg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_14ICi0cjEeml4OmTM0FgHg" x="924" y="172" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_14ICrUcjEeml4OmTM0FgHg" type="3027" element="_14ICjEcjEeml4OmTM0FgHg" fontName="DejaVu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_14ICrkcjEeml4OmTM0FgHg" type="5017" element="_14ICjEcjEeml4OmTM0FgHg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_14ICr0cjEeml4OmTM0FgHg" x="728" y="168" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_14IpmUcjEeml4OmTM0FgHg" type="3027" element="_14IpkEcjEeml4OmTM0FgHg" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_14IpmkcjEeml4OmTM0FgHg" type="5017" element="_14IpkEcjEeml4OmTM0FgHg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_14Ipm0cjEeml4OmTM0FgHg" x="398" y="332" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hDeLAEcnEeml4OmTM0FgHg" type="3062" element="_hDc84EcnEeml4OmTM0FgHg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_hDeLAkcnEeml4OmTM0FgHg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hDeLA0cnEeml4OmTM0FgHg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hDeLAUcnEeml4OmTM0FgHg" x="1142" y="187"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hwqBIEcnEeml4OmTM0FgHg" type="3062" element="_hwpaEEcnEeml4OmTM0FgHg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_hwqBIkcnEeml4OmTM0FgHg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hwqBI0cnEeml4OmTM0FgHg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hwqBIUcnEeml4OmTM0FgHg" x="610" y="347"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A8Tp8Ey8EemBcOD5CMOafw" type="3027" element="_A8RNsEy8EemBcOD5CMOafw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_A8URAEy8EemBcOD5CMOafw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A8Tp8Uy8EemBcOD5CMOafw" x="1845" y="108" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_x5qCXPSMEeeYpYD60oU_zA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_x5qCXfSMEeeYpYD60oU_zA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_x5qCXvSMEeeYpYD60oU_zA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_x5qCX_SMEeeYpYD60oU_zA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x5qCYPSMEeeYpYD60oU_zA" x="18" y="10" width="1657" height="757"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_x5qCYfSMEeeYpYD60oU_zA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_x5qCYvSMEeeYpYD60oU_zA" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_x5qCY_SMEeeYpYD60oU_zA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_x5qCZPSMEeeYpYD60oU_zA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x5qCZfSMEeeYpYD60oU_zA" width="2221" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_x5qCZvSMEeeYpYD60oU_zA"/>
    <edges xmi:type="notation:Connector" xmi:id="_14JQoEcjEeml4OmTM0FgHg" type="4001" element="_14IpnEcjEeml4OmTM0FgHg" source="_14GNXkcjEeml4OmTM0FgHg" target="_14ICrUcjEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_14JQoUcjEeml4OmTM0FgHg" type="6001" element="_14IpnEcjEeml4OmTM0FgHg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_14JQokcjEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_14JQo0cjEeml4OmTM0FgHg" fontName="DejaVu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_14JQpEcjEeml4OmTM0FgHg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_14J3s0cjEeml4OmTM0FgHg" type="4001" element="_14J3sEcjEeml4OmTM0FgHg" source="_14GNbUcjEeml4OmTM0FgHg" target="_14IpmUcjEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_14J3tEcjEeml4OmTM0FgHg" type="6001" element="_14J3sEcjEeml4OmTM0FgHg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_14J3tUcjEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_14J3tkcjEeml4OmTM0FgHg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_14J3t0cjEeml4OmTM0FgHg" points="[-2, 19, -171, -67]$[-2, 85, -171, -1]$[119, 85, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_14Kew0cjEeml4OmTM0FgHg" type="4001" element="_14KewEcjEeml4OmTM0FgHg" source="_14GNbUcjEeml4OmTM0FgHg" target="_14HbxEcjEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_14KexEcjEeml4OmTM0FgHg" type="6001" element="_14KewEcjEeml4OmTM0FgHg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_14KexUcjEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_14KexkcjEeml4OmTM0FgHg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_14Kex0cjEeml4OmTM0FgHg" points="[-22, -31, -266, 54]$[-22, -82, -266, 3]$[235, -82, -9, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_14KeyEcjEeml4OmTM0FgHg" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_14KeyUcjEeml4OmTM0FgHg" id="(0.075,0.2833333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_14KezUcjEeml4OmTM0FgHg" type="4001" element="_14KeykcjEeml4OmTM0FgHg" source="_14HbxEcjEeml4OmTM0FgHg" target="_14GNXkcjEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_14KezkcjEeml4OmTM0FgHg" type="6001" element="_14KeykcjEeml4OmTM0FgHg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_14Kez0cjEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_14Ke0EcjEeml4OmTM0FgHg" fontName="DejaVu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_14Ke0UcjEeml4OmTM0FgHg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_14LF00cjEeml4OmTM0FgHg" type="4001" element="_14LF0EcjEeml4OmTM0FgHg" source="_14ICrUcjEeml4OmTM0FgHg" target="_14ICiUcjEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_14LF1EcjEeml4OmTM0FgHg" type="6001" element="_14LF0EcjEeml4OmTM0FgHg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_14LF1UcjEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_14LF1kcjEeml4OmTM0FgHg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_14LF10cjEeml4OmTM0FgHg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zwsEoEcSEeml4OmTM0FgHg" type="4003" element="_UF8iCODjEeioZo4elrUmvw" source="_t2nQsPYZEeesarEo_Te_Dg" target="_EemD0PYSEeesarEo_Te_Dg">
      <styles xmi:type="notation:FontStyle" xmi:id="_zwsEoUcSEeml4OmTM0FgHg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zwsEokcSEeml4OmTM0FgHg" points="[0, 39, 0, -80]$[0, 79, 0, -40]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hi8AIEclEeml4OmTM0FgHg" type="4001" element="_hi4VwEclEeml4OmTM0FgHg" source="_x5qCU_SMEeeYpYD60oU_zA" target="_14GNbUcjEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hi8AI0clEeml4OmTM0FgHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hi8AJEclEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hi8AIUclEeml4OmTM0FgHg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hi8AIkclEeml4OmTM0FgHg" points="[0, 0, -109, -2]$[113, -16, 4, -18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hi-cYEclEeml4OmTM0FgHg" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hDh1YUcnEeml4OmTM0FgHg" type="4001" element="_hDhOUEcnEeml4OmTM0FgHg" source="_14ICiUcjEeml4OmTM0FgHg" target="_hDeLAEcnEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hDh1ZEcnEeml4OmTM0FgHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hDh1ZUcnEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hDh1YkcnEeml4OmTM0FgHg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hDh1Y0cnEeml4OmTM0FgHg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hwrPQ0cnEeml4OmTM0FgHg" type="4001" element="_hwrPQEcnEeml4OmTM0FgHg" source="_14IpmUcjEeml4OmTM0FgHg" target="_hwqBIEcnEeml4OmTM0FgHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hwr2UEcnEeml4OmTM0FgHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hwr2UUcnEeml4OmTM0FgHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hwrPREcnEeml4OmTM0FgHg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hwrPRUcnEeml4OmTM0FgHg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
